src-git-full packages https://git.openwrt.org/feed/packages.git^d057936acbefd76b033e7c365baa68b48ccb9166
src-git-full luci https://git.openwrt.org/project/luci.git^0b38d70fbd47b0c702d5001de623213eb301a6fe
src-git-full routing https://git.openwrt.org/feed/routing.git^1cc7676b9f32acc30ec47f15fcb70380d5d6ef01
#src-link custom /usr/src/openwrt/custom-feed
src-link qtibsp ../owrt-qti-bsp
src-link qticore ../owrt-qti-core/recipes
src-link qticoreprop ../owrt-qti-core-prop/packages
src-link qtibspprop ../owrt-qti-bsp-prop
src-link qtinternal ../owrt-qti-internal
src-link qtissmgr ../owrt-qti-ss-mgr/recipes
src-link qtissmgrprop ../owrt-qti-ss-mgr-prop/recipes
src-link qtilocation ../owrt-qti-location
src-link qtiargs ../owrt-qti-args/openwrt
src-link qtiaudio ../owrt-qti-audio/openwrt
src-link qtiaudioprop ../owrt-qti-audio-prop/openwrt
src-link qtilocationprop ../owrt-qti-location-prop
src-link qtilocationinternal ../owrt-qti-location-internal
src-link qtiagm ../owrt-qti-agm/openwrt
src-link qtipal ../owrt-qti-pal/openwrt
src-link qtidataprop ../owrt-qti-data-prop
src-link qtidata ../owrt-qti-data
src-link qtidatainternal ../owrt-qti-data-internal
src-link qtirilprop ../owrt-qti-ril-prop/
src-link qtibt ../owrt-qti-bt/openwrt
src-link qtibtprop ../owrt-qti-bt-prop/openwrt
src-link qtiwlan ../owrt-qti-wlan
src-link qtiwlanprop ../owrt-qti-wlan-prop
src-link qtictainternal ../owrt-qti-cta-internal
src-link qtisecurity ../owrt-qti-security/recipes
src-link qtisecurityprop ../owrt-qti-security-prop/recipes
src-link qtisecurityinternal ../owrt-qti-security-internal/recipes
src-link qtissdk ../owrt-qti-ssdk/
src-link qtimsdcprop ../owrt-qti-msdc-prop
src-link qtiipqprop ../owrt-qti-ipq-prop/feeds
src-link qtiipq ../owrt-qti-ipq/feeds
src-link qticoreinternal ../owrt-qti-core-internal/packages
src-link qtiperfprop ../owrt-qti-perf-prop/recipes
src-link qtisensorsinternal ../owrt-qti-sensors-internal
src-link qtisensorsprop ../owrt-qti-sensors-prop
src-link qtippatprop ../owrt-qti-ppat-prop/openwrt
src-link qtiipqezmesh ../owrt-qti-ipq-ezmesh/feeds
