src-git packages https://source.codeaurora.org/quic/le/owrt/feeds/packages;packages/github-openwrt/openwrt-21.02
src-git luci https://source.codeaurora.org/quic/le/owrt/feeds/luci;luci/github-openwrt/openwrt-21.02
src-git routing https://source.codeaurora.org/quic/le/owrt/feeds/routing;routing/github/openwrt-21.02
#src-link custom /usr/src/openwrt/custom-feed
src-link qtibsp ../owrt-qti-bsp
src-link qticoreprop ../meta-qti-core-prop/recipes
src-link qtibspprop ../owrt-qti-bsp-prop/bsp-packages
src-link qtissmgr ../meta-qti-ss-mgr/recipes
src-link qtissmgrprop ../meta-qti-ss-mgr-prop/recipes
src-link qtilocation ../meta-qti-location/recipes/location
