src-git packages https://git.codelinaro.org/clo/le/owrt/feeds/packages.git^cd3dc69d6b8fa135a656fd11b63a25d53bcdb84f
src-git luci https://git.codelinaro.org/clo/le/owrt/feeds/luci.git^1cf976c2b3faa28f7416f11babbb9128dff29520
src-git routing https://git.codelinaro.org/clo/le/owrt/feeds/routing.git^bfd645b8a89c3960584191e78a095e2ba4fb66a2
#src-link custom /usr/src/openwrt/custom-feed
src-link qtibsp ../owrt-qti-bsp
src-link qticore ../owrt-qti-core/recipes
src-link qticoreprop ../owrt-qti-core-prop/packages
src-link qtibspprop ../owrt-qti-bsp-prop
src-link qtissmgr ../owrt-qti-ss-mgr/recipes
src-link qtissmgrprop ../owrt-qti-ss-mgr-prop/recipes
src-link qtilocation ../owrt-qti-location
src-link qtiargs ../owrt-qti-args/openwrt
src-link qtiaudio ../owrt-qti-audio/openwrt
src-link qtiaudioprop ../owrt-qti-audio-prop/openwrt
src-link qtilocationprop ../owrt-qti-location-prop
src-link qtiagm ../owrt-qti-agm/openwrt
src-link qtipal ../owrt-qti-pal/openwrt
src-link qtidataprop ../owrt-qti-data-prop
src-link qtidata ../owrt-qti-data
src-link qtidatainternal ../owrt-qti-data-internal
src-link qtirilprop ../owrt-qti-ril-prop/
src-link qtiwlan ../owrt-qti-wlan
src-link qtiwlanprop ../owrt-qti-wlan-prop
