src-git packages https://github.com/openwrt/packages.git^e8a705e21e37c0c8b54750c3cb0df09056c704b9 https://git.codelinaro.org/clo/le/owrt/feeds/packages.git^e8a705e21e37c0c8b54750c3cb0df09056c704b9
#src-link custom /usr/src/openwrt/custom-feed
src-link qtibsp ../owrt-qti-bsp
src-link qticore ../owrt-qti-core/recipes
src-link qticoreprop ../owrt-qti-core-prop/packages
src-link qtibspprop ../owrt-qti-bsp-prop
src-link qtinternal ../owrt-qti-internal
src-link qtigplv2 ../owrt-qti-gplv2
