src-git packages https://github.com/openwrt/packages.git^e8a705e21e37c0c8b54750c3cb0df09056c704b9 https://git.codelinaro.org/clo/le/owrt/feeds/packages.git^e8a705e21e37c0c8b54750c3cb0df09056c704b9
src-git luci https://github.com/openwrt/luci.git^6da5e65981734021932b8d339ce7a386eb8f8476 https://git.codelinaro.org/clo/le/owrt/feeds/luci.git^6da5e65981734021932b8d339ce7a386eb8f8476
src-git routing https://github.com/openwrt/routing.git^d8f9eab170bb63024596c4133c04a84a7aa8a454 https://git.codelinaro.org/clo/le/owrt/feeds/routing.git^d8f9eab170bb63024596c4133c04a84a7aa8a454
#src-link custom /usr/src/openwrt/custom-feed
src-link qtibsp ../owrt-qti-bsp
src-link qticore ../owrt-qti-core/recipes
src-link qticoreprop ../owrt-qti-core-prop/packages
src-link qtibspprop ../owrt-qti-bsp-prop
src-link qtinternal ../owrt-qti-internal
src-link qtissmgr ../owrt-qti-ss-mgr/recipes
src-link qtissmgrprop ../owrt-qti-ss-mgr-prop/recipes
src-link qtilocation ../owrt-qti-location
src-link qtiaudio ../owrt-qti-audio
src-link qtiaudioalgos ../owrt-qti-audio-algos
src-link qtilocationprop ../owrt-qti-location-prop
src-link qtilocationinternal ../owrt-qti-location-internal
src-link qtirilprop ../owrt-qti-ril-prop/
src-link qtibt ../owrt-qti-bt/openwrt
src-link qtibtprop ../owrt-qti-bt-prop/openwrt
src-link qtiwlan ../owrt-qti-wlan
src-link qtiwlanprop ../owrt-qti-wlan-prop
src-link qtictainternal ../owrt-qti-cta-internal
src-link qtisecurity ../owrt-qti-security/recipes
src-link qtisecurityprop ../owrt-qti-security-prop/recipes
src-link qtisecurityinternal ../owrt-qti-security-internal/recipes
src-link qtissdk ../owrt-qti-ssdk/
src-link qtimsdcprop ../owrt-qti-msdc-prop
src-link qtiipqprop ../owrt-qti-ipq-prop/feeds
src-link qtiipq ../owrt-qti-ipq/feeds
src-link qticoreinternal ../owrt-qti-core-internal/packages
src-link qtiperfprop ../owrt-qti-perf-prop/recipes
src-link qtisensorsinternal ../owrt-qti-sensors-internal
src-link qtisensorsprop ../owrt-qti-sensors-prop
src-link qtippatprop ../owrt-qti-ppat-prop/openwrt
#src-link qtiipqezmesh ../owrt-qti-ipq-ezmesh/feeds
src-link qtigplv2 ../owrt-qti-gplv2
src-link qtidataprop ../owrt-qti-data-prop
src-link qtidata ../owrt-qti-data
src-link qtidatainternal ../owrt-qti-data-internal
src-link qtitelsdk ../owrt-qti-telsdk
src-link qtitelsdkprop ../owrt-qti-telsdk-prop
src-link qtiemergencyalertprop ../owrt-qti-emergencyalert-prop