src-git-full packages git://git-android.quicinc.com/owrt/feeds/packages.git^ceda7c95ffcc296442f2e0b9249c66219e0deb80 https://git.codelinaro.org/clo/le/owrt/feeds/packages.git^ceda7c95ffcc296442f2e0b9249c66219e0deb80
src-git-full luci git://git-android.quicinc.com/owrt/feeds/luci.git^23657ad52c3d5d89f79e497681069d25597065fb https://git.codelinaro.org/clo/le/owrt/feeds/luci.git^23657ad52c3d5d89f79e497681069d25597065fb
src-git-full routing git://git-android.quicinc.com/owrt/feeds/routing.git^0ff4ab0506f2ab09b829699bef6b8be8bf8f87f1 https://git.codelinaro.org/clo/le/owrt/feeds/routing.git^0ff4ab0506f2ab09b829699bef6b8be8bf8f87f1
#src-link custom /usr/src/openwrt/custom-feed
src-link qtibsp ../owrt-qti-bsp
src-link qticore ../owrt-qti-core/recipes
src-link qticoreprop ../owrt-qti-core-prop/packages
src-link qtibspprop ../owrt-qti-bsp-prop
src-link qtinternal ../owrt-qti-internal
src-link qtissmgr ../owrt-qti-ss-mgr/recipes
src-link qtissmgrprop ../owrt-qti-ss-mgr-prop/recipes
src-link qtilocation ../owrt-qti-location
src-link qtiaudio ../owrt-qti-audio
src-link qtiaudioalgos ../owrt-qti-audio-algos
src-link qtilocationprop ../owrt-qti-location-prop
src-link qtilocationinternal ../owrt-qti-location-internal
src-link qtirilprop ../owrt-qti-ril-prop/
src-link qtibt ../owrt-qti-bt/openwrt
src-link qtibtprop ../owrt-qti-bt-prop/openwrt
src-link qtiwlan ../owrt-qti-wlan
src-link qtiwlanprop ../owrt-qti-wlan-prop
src-link qtictainternal ../owrt-qti-cta-internal
src-link qtisecurity ../owrt-qti-security/recipes
src-link qtisecurityprop ../owrt-qti-security-prop/recipes
src-link qtisecurityinternal ../owrt-qti-security-internal/recipes
src-link qtissdk ../owrt-qti-ssdk/
src-link qtimsdcprop ../owrt-qti-msdc-prop
src-link qtiipqprop ../owrt-qti-ipq-prop/feeds
src-link qtiipq ../owrt-qti-ipq/feeds
src-link qticoreinternal ../owrt-qti-core-internal/packages
src-link qtiperfprop ../owrt-qti-perf-prop/recipes
src-link qtisensorsinternal ../owrt-qti-sensors-internal
src-link qtisensorsprop ../owrt-qti-sensors-prop
src-link qtippatprop ../owrt-qti-ppat-prop/openwrt
#src-link qtiipqezmesh ../owrt-qti-ipq-ezmesh/feeds
src-link qtigplv2 ../owrt-qti-gplv2
src-link qtidataprop ../owrt-qti-data-prop
src-link qtidata ../owrt-qti-data
src-link qtidatainternal ../owrt-qti-data-internal
